# Generated by Django 3.1.6 on 2021-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210301_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.CharField(default='https://i.ibb.co/6nTkL30/Unknown-Product.png', max_length=250),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='__', max_length=100),
        ),
    ]
