version: "3.7"

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db && \
                    python manage.py migrate && \
                    python manage.py create_groups && \
                    python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=shoppingapp
            - DB_USER=shoppingpostgres
            - DB_PASS=postgrespassword
        depends_on:
            - db
    
    db:
        image: postgres
        environment:
            - POSTGRES_DB=shoppingapp
            - POSTGRES_USER=shoppingpostgres
            - POSTGRES_PASSWORD=postgrespassword