# Generated by Django 3.1.6 on 2021-03-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210322_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available'), ('Pending Admin Confirmation', 'Pending Admin Confirmation')], default='Not Available', max_length=63),
        ),
    ]
